
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: mnist-train 
spec: 
  selector: 
    matchLabels: 
      app: mnist-train
  replicas: 2
  template: 
    metadata: 
      labels: 
        app: mnist-train
    spec: 
      containers: 
      - name: mnist-train
        image: siddpatny/mnist-train:latest 
        ports: 
        - containerPort: 8001
